[technote]
id = "TSTN-049"
series_id = "TSTN"
canonical_url = "https://tstn-049.lsst.io"
github_url = "https://github.com/lsst-tstn/tstn-049"
github_default_branch = "main"
date_created = 2024-11-21T13:03:49Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Parker"
name.family = "Fagrelius"
internal_id = "fagreliusp"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
